### ISSUE TITLE
Redraw of arena, climb position

### ISSUE THREAD

**Issue by PatheticMustan** [rebels2638/ScoutingApp2022#10]
It would be better to have a re-draw of the arena to make it cleaner.
![2022Field](https://user-images.githubusercontent.com/35382971/152864508-91e39afa-825c-4843-8ee0-a4d37ca31173.png)

If possible, a design with more contrast for text visibility, and maybe cooler colors B)

**Comment by 00100000** [comment]
i gotchu fam
![9DF8E9BD-C474-4F20-AD8B-B15F3FDBA887](https://user-images.githubusercontent.com/53249541/152866402-c8d3f2ff-afe2-4610-a9da-21782a106487.jpeg)

**Comment by PatheticMustan** [comment]
wow thanks aidan i'll be sure to use this in the app, 10/10 drawing

**Comment by PatheticMustan** [comment]
we may also need a new drawing for climb position...? do we have any groovy groovy artists?

**Comment by PatheticMustan** [comment]
not important
