### ISSUE TITLE
state issues: resetting/loading textboxes and timers

### ISSUE THREAD

**Issue by PatheticMustan** [rebels2638/ScoutingApp2022#18]
https://github.com/PatheticMustan/ScoutingApp2019/issues/36

trying to think it through, i'll try to explain as best i can
in the input components, there are two different types of state. redux state, and component state.

Redux state is slow, but globally accessible. it should eventually have all the true input values.
Component state is only accessible inside the input component itself, but is much faster.

For simple buttons like RadioButton, BoolButton, and NumButton, just storing everything in Redux State is good enough:tm:.

For complex components like textbox and timer, we have to come up with a much more complicated mix.
The lag from only using redux state would be too noticeable for textboxes, and rubberbanded the text constantly.
For timer, it would be too inefficient to spam redux state updates every single second. It would also have a noticeable (and inconsistent?) delay.
To fix these performance issues, we have the component state reflect the real values (fast but local), and update the redux state
every so often. In the case of textbox, every 0.5 seconds. For timer, whenever it's started/stopped.

For normal usage, this gross mix of component state and redux state is completely fine, but when we want to reset/load another match, we change the state from redux.
Because the redux state doesn't actually reflect the true value of the textbox/timer, they don't update. (???)

in 2020, we [tried fixing this issue](https://github.com/PatheticMustan/ScoutingApp2019/issues/36) with a SEPERATE component state.

What we want to do is make a cleaner way to handle this issue, maybe a custom handler for component/redux state...?
Our current implementation is too complicated, and nobody (??? how did i even write this code) can fix it when it's broken,
or when we need to copy it over to another component.

If we can give Timer this same mix of component/redux state, it would be cool, but it'd be even cooler to have a simpler, permanent solution...!

**Comment by PatheticMustan** [comment]
one of the solutions i was thinking about was having the textbox/timer load a default value OR whatever was currently in the redux store. That way, we'd be able to just set the stuff in redux, and quickly unmount/mount the scouting page.

this is SUPER scuffed, but would be much cleaner than any wrapper i'd be able to write....???

**Comment by PatheticMustan** [comment]
@00100000 please help me i can't do this on my own

**Comment by 00100000** [comment]
I don't know anything about redux. I'm not sure if I CAN help unless you give me a while to learn it.

**Comment by PatheticMustan** [comment]
WAIT NEVERMIND I'M A GOD I KNOW THE SOLUTION

**Comment by PatheticMustan** [comment]
the issue is solved. to summarize

our simpler components only use redux, but some components (textbox/timer) use a blend of component state and redux state for performance reasons.
loading and resetting worked perfectly fine for the simpler components, but when it came to the blended components, the component state overwrote the new redux state. This meant loading/resetting matches wouldn't do anything.

our fix was to have a seperate `blendedState` in redux. `blendedState` has all the keys, but the values are always null.
it will only update on match reset/load, which means we can use it to do stuff


huzzah, a drawing
![image](https://user-images.githubusercontent.com/35382971/156947695-9064c854-4b0f-466a-a003-64e7e01da60d.png)
